Consul-SyncTask:
  policy: "Enterprise/MasterTemplate/Consul-CatalogSync"
  isOneNode: false
  jobType: "Recurring"
  jobStatus: "Scheduled"
  cronExpression: "*/15 * * * * ?"
  shouldExecuteOnCreate: true
  properties: {}
