ephemeral.aws.com:
  verifyHostname: false
  trustedForSsl: true
  trustedAsSamlAttestingEntity: true
  trustAnchor: true
  revocationCheckingEnabled: true
  trustedForSigningClientCerts: true
  trustedForSigningServerCerts: true
  trustedAsSamlIssuer: true
localhost:
  verifyHostname: false
  trustedForSsl: true
  trustedAsSamlAttestingEntity: true
  trustAnchor: true
  revocationCheckingEnabled: true
  trustedForSigningClientCerts: true
  trustedForSigningServerCerts: true
  trustedAsSamlIssuer: true
