gmu/SAMPLE2:
  url: "/rest/apicall"
  policy: "gmu/SAMPLE2"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
gmu/SAMPLE1:
  url: "/gmu/apicall"
  policy: "gmu/SAMPLE1"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties:
    env: "sandbox1"
  wssProcessingEnabled: false
