AWS:
  policy: "AWS-SK/AWS"
  arguments:
  - name: "config"
    type: "string"
    requireExplicit: true
  results:
  - name: "aws.responseCode"
    type: "int"
  - name: "result"
    type: "string"
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "true"
    passMetricsToParent: "false"
